(function (global) {
  "use strict";

  var locale = Object.freeze({
    "ui.settings": "Settings",
    "ui.config_analyze": "Config Analyze",
    "ui.seed": "Seed:",
    "ui.max_ante": "Max Ante:",
    "ui.cards_per_ante": "Cards per Ante:",
    "ui.deck": "Deck:",
    "ui.stake": "Stake:",
    "ui.version": "Version:",
    "ui.analyze": "Analyze",
    "ui.summarize": "Summarize",
    "ui.copy_summary": "Copy Summary",
    "ui.download_output": "Download output",
    "ui.copy_link": "Copy Link",
    "ui.modify_unlocks": "Modify Unlocks",
    "ui.omit_before_ante9": "Omit results before Ante 9",
    "ui.unlocked_items": "Unlocked Items",
    "ui.submit": "Submit",
    "ui.unlock_all": "Unlock All",
    "ui.lock_all": "Lock All",
    "ui.summary": "Summary",
    "ui.search": "Search",
    "ui.filter": "Filter",
    "ui.intro": "Intro",
    "ui.ui_tips": "UI Tips",
    "ui.settings_top": "Settings (Top)",
    "ui.emoji": "Emoji",
    "ui.emoji_legend": "Emoji Legend",
    "ui.in_packs_marker": "In packs marker",
    "ui.negative_marker": "Negative marker",
    "ui.king_cards": "King Cards",
    "ui.emojis_visible": "Emojis in summary: visible",
    "ui.emojis_hidden": "Emojis in summary: hidden",
    "ui.analyze_failed": "Analyze failed. Check seed/version and try again.",
    "ui.analyze_too_large": "Analyze workload is too large. Reduce Max Ante or Cards per Ante.",
    "ui.color_default": "Summary text color: default",
    "ui.color_colorful": "Summary text color: colorful",
    "ui.nearby_visible": "Nearby Summaries: visible",
    "ui.nearby_hidden": "Nearby Summaries: hidden",
    "ui.nothing_to_summarize": "Nothing to summarize yet.",
    "ui.nothing_to_download": "Nothing to download yet.",
    "ui.link_copied": "Link copied to clipboard!",
    "ui.summary_copied": "Summary copied to clipboard!",
    "ui.copy_failed": "Failed to copy summary.",
    "ui.summary_placeholder": "Summary will appear here after you click Analyze.",
    "ui.no_tracking_items": "No tracking items",
    "ui.summarizing": "Summarizing results...",
    "ui.ante_navigation": "Ante Navigation",
    "ui.tap_to_jump": "Tap to jump",
    "ui.back_to_top": "Back to top",
    "ui.nearby_summaries": "Nearby Summaries",
    "ui.no_summary_yet": "No summary yet",
    "ui.packs": "Packs",
    "ui.all_packs": "All Packs",
    "ui.spectral_buffoon": "Spectral&Buffoon",
    "ui.standard": "Standard",
    "ui.arcana": "Arcana",
    "ui.celestial": "Celestial",
    "ui.voucher": "Voucher",
    "ui.tags": "Tags",
    "ui.boss": "Boss",
    "ui.ante": "Ante",
    "ui.page": "Page",
    "ui.previous": "Previous",
    "ui.next": "Next",
    "ui.search_filters": "Search Filters",
    "ui.tip_click_ante": "Click Ante badge in Summary to jump to that Ante in main page.",
    "ui.tip_double_click": "Double-click a Summary row to mark it finished and move it to bottom; double-click again to restore.",
    "ui.tip_nearby_scroll": "In Nearby Summaries, text can scroll left/right; click an entry to open its popup detail.",
    "ui.tip_settings_emoji": "In top-right Settings window, emoji icon buttons are Joker trackers.",
    "ui.tip_icon_sync": "These icon buttons sync with Search Filters > Jokers (same cards, two entry points).",
    "ui.tip_select_all": "Search Filters: Select all / Remove all also toggles those Joker tracker icons.",
    "ui.tip_hit_only": "Hit-only groups (\u25CE / \u25C9) are based on current highlights: search input + active Search Filters.",
    "ui.icon_only_buttons": "Icon-only buttons",
    "ui.open_search_window": "Open search window",
    "ui.toggle_card_layout": "Toggle card layout in each Ante (grid/carousel)",
    "ui.toggle_hit_only": "Toggle hit-only groups in each Ante",
    "ui.select_all": "Select all",
    "ui.remove_all": "Remove all",
    "ui.search_hint": "Press Enter to search (use , or \uFF0C; Chinese min 1 char, English min 3 chars)",
    "ui.search_placeholder": "Enter search terms (use , or \uFF0C)",
    "ui.jokers": "Jokers:",
    "ui.spectrals": "Spectrals:",
    "ui.vouchers": "Vouchers:",
    "ui.tags_label": "Tags:",
    "ui.bosses": "Bosses:",
    "ui.group_size": "Group Size:",
    "ui.switch_to_grid": "Switch to Grid",
    "ui.switch_to_carousel": "Switch to Carousel",
    "ui.cards_this_ante": "Cards (this Ante)",
    "ui.cards_this_ante_label": "Cards (this Ante):",
    "ui.rerun": "Re-run",
    "ui.restore": "Restore",
    "ui.jump": "Jump",
    "ui.jump_to_card": "Jump to card #",
    "ui.hide_non_hit": "Hide non-hit groups",
    "ui.only_groups_with_hits": "Only groups with hits",
    "ui.show_all_groups": "Show all groups"
  });

  if (typeof module === "object" && module.exports) {
    module.exports = locale;
  }
  if (global) {
    global.BalatroUiLocale_enUS = locale;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
