(function (global) {
  "use strict";

  var locale = Object.freeze({
    "Settings": "设置",
    "Config Analyze": "预测配置",
    "Seed:": "种子：",
    "Max Ante:": "最高底注：",
    "Cards per Ante:": "每底注牌数：",
    "Deck:": "牌组：",
    "Stake:": "赌注：",
    "Version:": "版本：",
    "Analyze": "生成预测",
    "Summarize": "总结",
    "Copy Summary": "复制总结",
    "Download output": "下载输出",
    "Copy Link": "复制链接",
    "Modify Unlocks": "修改解锁",
    "Omit results before Ante 9": "省略底注 9 前的结果",
    "Unlocked Items": "已解锁项目",
    "Submit": "提交",
    "Unlock All": "全部解锁",
    "Lock All": "全部锁定",
    "Summary": "总结",
    "Search": "搜索",
    "Filter": "筛选",
    "Intro": "说明",
    "UI Tips": "功能提示",
    "Settings (Top)": "设置",
    "Emoji": "Emoji",
    "Emoji Legend": "Emoji说明",
    "In packs marker": "在卡包中出现（此标记始终显示）",
    "Negative marker": "表示负片",
    "King Cards": "K牌",
    "Emojis: visible": "Emoji：显示",
    "Emojis: hidden": "Emoji：隐藏",
    "Analyze failed. Check seed/version and try again.": "分析失败，请检查种子或版本后重试。",
    "Analyze workload is too large. Reduce Max Ante or Cards per Ante.": "分析规模过大，请降低最高底注或每底注牌数。",
    "Text Color: default": "文本颜色：单色",
    "Text Color: colorful": "文本颜色：多彩",
    "Nearby Summaries: visible": "最近4注总结：显示",
    "Nearby Summaries: hidden": "最近4注总结：隐藏",
    "Nothing to summarize yet.": "暂无可总结内容。",
    "Nothing to download yet.": "暂无可下载内容。",
    "Link copied to clipboard!": "链接已复制到剪贴板！",
    "Summary copied to clipboard!": "总结已复制到剪贴板！",
    "Failed to copy summary.": "复制总结失败。",
    "Summary will appear here after you click Analyze.": "点击“分析”后会显示总结。",
    "No tracking items": "暂无追踪项",
    "Summarizing results...": "正在生成总结...",
    "Ante Navigation": "底注导航",
    "Tap to jump": "点击按钮跳转",
    "Back to top": "回到顶部",
    "Nearby Summaries": "最近4注总结",
    "No summary yet": "暂无总结",
    "Packs": "补充包",
    "All Packs": "全部补充包",
    "Spectral&Buffoon": "幻灵&小丑",
    "Standard": "标准",
    "Arcana": "秘术",
    "Celestial": "星球",
    "Voucher": "优惠券",
    "Tags": "标签",
    "Boss": "Boss",
    "Ante": "底注",
    "Page": "页",
    "Previous": "上一页",
    "Next": "下一页",
    "Search Filters": "搜索筛选",
    "Click Ante badge in Summary to jump to that Ante in main page.": "在总结浮窗中点击底注按钮，可跳转到主页面 对应底注。",
    "Double-click a Summary row to mark it finished and move it to bottom; double-click again to restore.": "双击某条总结可标记为完成并移到底部；再次双击可恢复。",
    "In Nearby Summaries, text can scroll left/right; click an entry to open its popup detail.": "在最近4注总结中，文本可左右滚动；点击某条可弹出详情窗口。",
    "In top-right Settings window, emoji icon buttons are Joker trackers.": "右上角“设置”浮窗中的 Emoji 图标按钮是小丑追踪开关。",
    "These icon buttons sync with Search Filters > Jokers (same cards, two entry points).": "这些图标会与“搜索筛选 > 小丑”同步（同一批卡牌，两种入口）。",
    "Search Filters: Select all / Remove all also toggles those Joker tracker icons.": "“搜索筛选”中的“全选 / 清空”也会同时切换这些小丑图标开关。",
    "Hit-only groups (◎ / ◉) are based on current highlights: search input + active Search Filters.": "“仅显示命中分组”(◎ / ◉)依据搜索输入 + 已启用的搜索筛选目标卡牌。",
    "Icon-only buttons": "仅图标按钮说明",
    "Open search window": "打开搜索浮窗",
    "Toggle card layout in each Ante (grid/carousel)": "在每个底注牌组中切换布局（网格/走马灯）",
    "Toggle hit-only groups in each Ante": "在每个底注牌组中切换仅显示命中分组",
    "Select all": "全选",
    "Remove all": "清空",
    "Press Enter to search (use , or ，; Chinese min 1 char, English min 3 chars)": "按回车搜索（支持英文逗号 , 和中文逗号 ，；中文可 1 字，英文至少 3 字）",
    "Enter search terms (use , or ，)": "输入搜索词（使用 , 或 ， 分隔）",
    "Jokers:": "小丑：",
    "Spectrals:": "幻灵：",
    "Vouchers:": "优惠券：",
    "Tags:": "标签：",
    "Bosses:": "Boss：",
    "Group Size:": "商店槽位：",
    "Switch to Grid": "网格布局",
    "Switch to Carousel": "走马灯布局",
    "Cards (this Ante)": "重设本注牌数",
    "Cards (this Ante):": "重设本注牌数：",
    "Re-run": "重算",
    "Restore": "恢复",
    "Jump": "跳转",
    "Jump to card #": "跳至牌序号",
    "Hide non-hit groups": "仅显示命中",
    "Only groups with hits": "仅显示命中",
    "Show all groups": "显示全部"
  });

  if (typeof module === "object" && module.exports) {
    module.exports = locale;
  }
  if (global) {
    global.BalatroUiLocale_zhCN = locale;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
