(function (global) {
  "use strict";

  var locale = Object.freeze({
    "ui.settings": "设置",
    "ui.config_analyze": "预测配置",
    "ui.seed": "种子：",
    "ui.max_ante": "最高底注：",
    "ui.cards_per_ante": "每底注牌数：",
    "ui.deck": "牌组：",
    "ui.stake": "赌注：",
    "ui.version": "版本：",
    "ui.analyze": "生成预测",
    "ui.summarize": "总结",
    "ui.copy_summary": "复制总结",
    "ui.download_output": "下载输出",
    "ui.copy_link": "复制链接",
    "ui.modify_unlocks": "修改解锁",
    "ui.omit_before_ante9": "省略底注 9 前的结果",
    "ui.unlocked_items": "已解锁项目",
    "ui.submit": "提交",
    "ui.unlock_all": "全部解锁",
    "ui.lock_all": "全部锁定",
    "ui.summary": "总结",
    "ui.search": "搜索",
    "ui.filter": "筛选",
    "ui.intro": "说明",
    "ui.ui_tips": "功能提示",
    "ui.settings_top": "设置",
    "ui.emoji": "Emoji",
    "ui.emoji_legend": "Emoji说明",
    "ui.in_packs_marker": "在卡包中出现（此标记始终显示）",
    "ui.negative_marker": "表示负片",
    "ui.king_cards": "K牌",
    "ui.emojis_visible": "总结中的 Emoji：显示",
    "ui.emojis_hidden": "总结中的 Emoji：隐藏",
    "ui.analyze_failed": "分析失败，请检查种子或版本后重试。",
    "ui.analyze_too_large": "分析规模过大，请降低最高底注或每底注牌数。",
    "ui.color_default": "总结文本颜色：单色",
    "ui.color_colorful": "总结文本颜色：多彩",
    "ui.nearby_visible": "最近4注总结：显示",
    "ui.nearby_hidden": "最近4注总结：隐藏",
    "ui.cards_text_only": "大牌数模式：纯文字",
    "ui.cards_with_images": "大牌数模式：带图片",
    "ui.nothing_to_summarize": "暂无可总结内容。",
    "ui.nothing_to_download": "暂无可下载内容。",
    "ui.link_copied": "链接已复制到剪贴板！",
    "ui.summary_copied": "总结已复制到剪贴板！",
    "ui.copy_failed": "复制总结失败。",
    "ui.summary_placeholder": "点击「分析」后会显示总结。",
    "ui.no_tracking_items": "暂无追踪项",
    "ui.summarizing": "正在生成总结...",
    "ui.ante_navigation": "底注导航",
    "ui.tap_to_jump": "点击按钮跳转",
    "ui.back_to_top": "回到顶部",
    "ui.nearby_summaries": "最近4注总结",
    "ui.no_summary_yet": "暂无总结",
    "ui.packs": "补充包",
    "ui.all_packs": "全部补充包",
    "ui.spectral_buffoon": "幻灵&小丑",
    "ui.standard": "标准",
    "ui.arcana": "秘术",
    "ui.celestial": "星球",
    "ui.voucher": "优惠券",
    "ui.tags": "标签",
    "ui.boss": "Boss",
    "ui.ante": "底注",
    "ui.page": "页",
    "ui.previous": "上一页",
    "ui.next": "下一页",
    "ui.search_filters": "搜索筛选",
    "ui.tip_click_ante": "在总结浮窗中点击底注按钮，可跳转到主页面 对应底注。",
    "ui.tip_double_click": "双击某条总结可标记为完成并移到底部；再次双击可恢复。",
    "ui.tip_nearby_scroll": "在最近4注总结中，文本可左右滚动；点击某条可弹出详情窗口。",
    "ui.tip_settings_emoji": "右上角「设置」浮窗中的 Emoji 图标按钮是小丑追踪开关。",
    "ui.tip_icon_sync": "这些图标会与「搜索筛选 > 小丑」同步（同一批卡牌，两种入口）。",
    "ui.tip_select_all": "「搜索筛选」中的「全选 / 清空」也会同时切换这些小丑图标开关。",
    "ui.tip_hit_only": "「仅显示命中分组」(\u25CE / \u25C9)依据搜索输入 + 已启用的搜索筛选目标卡牌。",
    "ui.icon_only_buttons": "仅图标按钮说明",
    "ui.open_search_window": "打开搜索浮窗",
    "ui.toggle_card_layout": "在每个底注牌组中切换布局（网格/走马灯）",
    "ui.toggle_hit_only": "在每个底注牌组中切换仅显示命中分组",
    "ui.select_all": "全选",
    "ui.remove_all": "清空",
    "ui.search_hint": "按回车搜索（支持英文逗号 , 和中文逗号 ，；中文可 1 字，英文至少 3 字）",
    "ui.search_placeholder": "输入搜索词（使用 , 或 ， 分隔）",
    "ui.jokers": "小丑：",
    "ui.spectrals": "幻灵：",
    "ui.vouchers": "优惠券：",
    "ui.tags_label": "标签：",
    "ui.bosses": "Boss：",
    "ui.group_size": "商店槽位：",
    "ui.switch_to_grid": "网格布局",
    "ui.switch_to_carousel": "走马灯布局",
    "ui.cards_this_ante": "重设本注牌数",
    "ui.cards_this_ante_label": "重设本注牌数：",
    "ui.rerun": "重算",
    "ui.restore": "恢复",
    "ui.jump": "跳转",
    "ui.jump_to_card": "跳至牌序号",
    "ui.hide_non_hit": "仅显示命中",
    "ui.only_groups_with_hits": "仅显示命中",
    "ui.show_all_groups": "显示全部"
  });

  if (typeof module === "object" && module.exports) {
    module.exports = locale;
  }
  if (global) {
    global.BalatroUiLocale_zhCN = locale;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
