(function (global) {
  "use strict";

  var locale = Object.freeze({
    "Settings": "设置",
    "Config Analyze": "预测配置",
    "Seed:": "种子：",
    "Max Ante:": "最高底注：",
    "Cards per Ante:": "每底注牌数：",
    "Deck:": "牌组：",
    "Stake:": "赌注：",
    "Version:": "版本：",
    "Analyze": "生成预测",
    "Summarize": "总结",
    "Copy Summary": "复制总结",
    "Download output": "下载输出",
    "Copy Link": "复制链接",
    "Modify Unlocks": "修改解锁",
    "Omit results before Ante 9": "省略底注 9 前的结果",
    "Unlocked Items": "已解锁项目",
    "Submit": "提交",
    "Unlock All": "全部解锁",
    "Lock All": "全部锁定",
    "Summary": "总结",
    "Filter": "筛选",
    "Settings (Top)": "设置",
    "Emoji": "Emoji",
    "Emoji Legend": "Emoji说明",
    "In packs marker": "在卡包中出现（此标记始终显示）",
    "Negative marker": "表示负片",
    "King Cards": "K牌",
    "Emojis: visible": "Emoji：显示",
    "Emojis: hidden": "Emoji：隐藏",
    "Analyze failed. Check seed/version and try again.": "分析失败，请检查种子或版本后重试。",
    "Analyze workload is too large. Reduce Max Ante or Cards per Ante.": "分析规模过大，请降低最高底注或每底注牌数。",
    "Text Color: default": "文本颜色：单色",
    "Text Color: colorful": "文本颜色：多彩",
    "Nothing to summarize yet.": "暂无可总结内容。",
    "Nothing to download yet.": "暂无可下载内容。",
    "Link copied to clipboard!": "链接已复制到剪贴板！",
    "Summary copied to clipboard!": "总结已复制到剪贴板！",
    "Failed to copy summary.": "复制总结失败。",
    "Summary will appear here after you click Analyze.": "点击“分析”后会显示总结。",
    "Summarizing results...": "正在生成总结...",
    "Nearby Summaries": "最近4注总结",
    "No summary yet": "暂无总结",
    "Packs": "补充包",
    "All Packs": "全部补充包",
    "Spectral&Buffoon": "幻灵&小丑",
    "Standard": "标准",
    "Arcana": "秘术",
    "Celestial": "星球",
    "Voucher": "优惠券",
    "Tags": "标签",
    "Boss": "Boss",
    "Ante": "底注",
    "Page": "页",
    "Previous": "上一页",
    "Next": "下一页",
    "Search Filters": "搜索筛选",
    "Select all": "全选",
    "Remove all": "清空",
    "Press Enter to search (use , or ，; Chinese min 1 char, English min 3 chars)": "按回车搜索（支持英文逗号 , 和中文逗号 ，；中文可 1 字，英文至少 3 字）",
    "Enter search terms (use , or ，)": "输入搜索词（使用 , 或 ， 分隔）",
    "Jokers:": "小丑：",
    "Spectrals:": "幻灵：",
    "Vouchers:": "优惠券：",
    "Tags:": "标签：",
    "Bosses:": "Boss：",
    "Group Size:": "商店槽位：",
    "Switch to Grid": "切换网格布局",
    "Switch to Carousel": "切换走马灯布局",
    "Cards (this Ante):": "本底注牌数：",
    "Re-run": "重新预测",
    "Restore": "恢复图片",
    "Only groups with hits": "仅显示命中分组",
    "Show all groups": "显示全部分组"
  });

  if (typeof module === "object" && module.exports) {
    module.exports = locale;
  }
  if (global) {
    global.BalatroUiLocale_zhCN = locale;
  }
})(typeof globalThis !== "undefined" ? globalThis : this);
